# Generated by Django 3.1 on 2021-12-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='some_brand', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand'),
            preserve_default=False,
        ),
    ]
