# Generated by Django 3.1 on 2021-12-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211226_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
