# Generated by Django 3.1 on 2021-12-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211228_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
